version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maratona-api
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - maratona-network
      - app-network
    
  db:
    image: keinos/sqlite3
    container_name: maratona-db
    restart: always
    tty: true
    volumes: 
      - ./database.sqlite
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  maratona-network:
    external: true